package entity;

import java.util.Date;

public class Monkey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monkey.id
     *
     * @mbggenerated Sat Apr 20 11:13:45 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monkey.name
     *
     * @mbggenerated Sat Apr 20 11:13:45 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monkey.phone_number
     *
     * @mbggenerated Sat Apr 20 11:13:45 CST 2019
     */
    private Integer phoneNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monkey.birthday
     *
     * @mbggenerated Sat Apr 20 11:13:45 CST 2019
     */
    private Date birthday;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monkey
     *
     * @mbggenerated Sat Apr 20 11:13:45 CST 2019
     */
    public Monkey(Integer id, String name, Integer phoneNumber, Date birthday) {
        this.id = id;
        this.name = name;
        this.phoneNumber = phoneNumber;
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monkey.id
     *
     * @return the value of monkey.id
     *
     * @mbggenerated Sat Apr 20 11:13:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monkey.name
     *
     * @return the value of monkey.name
     *
     * @mbggenerated Sat Apr 20 11:13:45 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monkey.phone_number
     *
     * @return the value of monkey.phone_number
     *
     * @mbggenerated Sat Apr 20 11:13:45 CST 2019
     */
    public Integer getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monkey.birthday
     *
     * @return the value of monkey.birthday
     *
     * @mbggenerated Sat Apr 20 11:13:45 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }
}